### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by KennyTC** [google/googleapis.dart#486]
I  run a small example to extract characters from images using Google cloud  vision API  as below. Most of  the code is from here
[here](https://github.com/google/googleapis.dart/issues/67)
- pubspec.yaml
```
name: example2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  googleapis:
  googleapis_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - assets/credentials.json

```
- credentials.dart

```
import 'package:flutter/services.dart';
import 'package:googleapis/vision/v1.dart';
import 'package:googleapis_auth/auth_io.dart';

class CredentialsProvider {
  CredentialsProvider();

  Future<ServiceAccountCredentials> get _credentials async {
    String _file = await rootBundle.loadString('assets/credentials.json');
    return ServiceAccountCredentials.fromJson(_file);
  }

  Future<AutoRefreshingAuthClient> get client async {
    AutoRefreshingAuthClient _client = await clientViaServiceAccount(
        await _credentials, [VisionApi.cloudVisionScope]);
    // _client.close();
    return _client;
  }
}
```
- rekognize.dart
```
class RekognizeProvider {
  final _client = CredentialsProvider().client;

  void search(String image) async {
    var _vision = VisionApi(await _client);
    var _api = _vision.images;
    var _request = BatchAnnotateImagesRequest.fromJson({
      "requests": [
        {
          "image": {
            "content": image,
            // "content": image
          },
          "features": [
            {
              "type": "TEXT_DETECTION"
            }
          ]
        }
      ]
    });
    var _response = await _api.annotate(_request);
    _response.responses?.forEach((element) {
      TextAnnotation? x = element.fullTextAnnotation;
      if (x != null) {
        print("value:");
        print(x?.text.toString());
      }
    });
```
-  service.dart where to start the event
```
    RekognizeProvider recognizer = new  RekognizeProvider();
    final imgBase64Str = await networkImageToBase64("https://m.media-amazon.com/images/I/71HEeSeRwpL._SL1500_.jpg");
    recognizer.search(imgBase64Str);
```
Sometimes,  it works fine and give me  the results, but  sometimes,  I got   the following errors. 
```
D/EGL_emulation(23615): app_time_stats: avg=16457.89ms min=5.18ms max=131544.02ms count=8
E/flutter (23615): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (23615): 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))
E/flutter (23615): #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
E/flutter (23615): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
E/flutter (23615): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
E/flutter (23615): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
E/flutter (23615): <asynchronous suspension>
E/flutter (23615): 
```
It  seems  that I have  problems  with  Google  authentication?
