### ISSUE TITLE
removing the api name from `config.yaml` is not reflected when generating the package

### ISSUE THREAD

**Issue by AbhijithKonnayil** [google/googleapis.dart#675]
Even when I update the `config.yaml`, by removing some apis, it will still generate all the libraries corresponding to json files in discovery  

```
# Manually curated lists of which APIs should go into which packages, and which
# should be ignored.
packages:
- googleapis:
    version: 14.0.0
    repository: https://github.com/google/googleapis.dart/tree/master/generated/googleapis
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis/CHANGELOG.md
    example: resources/googleapis/examples/main.dart
    mono_pkg: resources/googleapis/_mono_pkg.yaml
    resolution: workspace
    extraDevDependencies:
        googleapis_auth: '>=1.0.0 <3.0.0'
    apis:
    - firebaseappdistribution:v1

```

even after keeping only only api, it generate the whole apis
